### ISSUE TITLE
Possible Wp Smush incompatibility?

### ISSUE THREAD

**Issue by DeliciousThemes** [wpexplorer/nova-wp-image-resizer#1]
Hey, 

This seems to be the best option to serve resized images on the fly from a CDN. However, it seems that there`s a slight issue when Wp SmushIt is enabled. 

`Fatal error: Uncaught Error: Call to undefined function get_current_screen() in wp-content/plugins/wp-smushit/lib/class-wp-smush-resize.php:56 Stack trace: #0 wp-content/plugins/wp-smushit/lib/class-wp-smush.php(612): WpSmushResize->initialize(true) #1 wp-includes/class-wp-hook.php(298): WpSmush->smush_image(Array, 416) #2 wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #3 wp-includes/post.php(5013): apply_filters('wp_update_attac...', Array, 416) #4 plugins/delicious-addons-mora/extend-vc/core/includes/nova-wp-image-resizer.php(197): wp_update_attachment_metadata(416, Array)`

From what I can tell, both plugins are using wp_update_attachment_metadata(); so this might be the issue. 

Just to let you know! 

Thanks!
Madalin

**Comment by wpexplorer** [comment]
@DeliciousThemes - That would be an error with the smushit plugin. The wp_update_attachment_metadata filter can be used anywhere, however, get_current_screen() only exists in the admin side. They should probably add an extra check to make sure their filter only runs in the admin side so they aren't doing extra work. I updated the script though to just use update_post_meta instead of the function to prevent issues with incorrectly coded plugins hooking into the filter ;)

**Comment by wpexplorer** [comment]
@DeliciousThemes By the way...you can use this script and hook into wp_get_attachment_image_src to dynamically resize any image that is passed through the filter. That way you can still use the default add_image_size and the_post_thumbnail() functions in your theme/plugin for archives and posts while also adding dynamic image support to any 3rd party plugin such as WooCommerce 8-) It's not very hard to do.

**Comment by DeliciousThemes** [comment]
That's awesome! Thanks for your quick reply and fix! I`ll be making use of the script for sure since Aqua Resizer seems to be out-of-date(not up to nowadays requirements, I would say). Your solution looks promising and I look forward to seeing it at work! :)

Cheers!

**Comment by wpexplorer** [comment]
@DeliciousThemes - Great!

Ps: I am planning the release of a plugin in the next 1-2 weeks I think called "Nova WP" and it will have the image resizing built-in. You just define image sizes in your theme and it will auto resize them and even add an admin panel so the end customer can change the settings, it's going to have tons of custom widgets, a few shortcodes, customizer theme options builder with live CSS/Typography settings, icon font libraries, term thumbnails, metabox class, gallery metabox, dashboard thumbnails...etc. Basically it will be a plugin that you can bundle with your theme's to make theme development much faster. Eventually it will have post types (portfolio, staff, etc)...

In the theme you would just use the add_theme_support to enable functions like this - https://cl.ly/lhbk - so nothing in the plugin will load unless the theme supports it. Easily declare image sizes with or without default values - https://cl.ly/liYq - easily declare Customizer settings/panels with inline_css that you can preview live in the Customizer and the CSS will output to the site on the front-end so very quick Customizer setting creation - https://cl.ly/lheI - and all the other good stuff mentioned above plus some!

Hopefully I can help people make themes faster and better with this added framework plugin. Definitely keep an eye out ;)

You do nice work over there at Delicious Themes if you ever want to team up on something and I have time or if you are ever looking for some extra work please hit me up wpexplorer at gmail dot com.

- AJ Clarke

**Comment by DeliciousThemes** [comment]
Hey AJ,

Thanks for the info! The plugin sounds like an awesome dev tool. If it helps to deploy themes faster, that would be even great! I`ll keep a very close eye on it!

Just sent you an email!

Cheers!
